test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
#   adapter: sqlite3
#   database: db/medphil.sqlite3
   adapter: postgresql
   encoding: utf-8
   database: hitili
   host: localhost
   username: lesoto

production:
  adapter: postgresql
  encoding: utf-8
  database: hitili
  port: 5432
  host: localhost
  pool: 5
  timeout: 5000

